// @bun @bytecode
// Claude Code is a Beta product per Anthropic's Commercial Terms of Service.
// By using Claude Code, you agree that all code acceptance or rejection decisions you make,
// and the associated conversations in context, constitute Feedback under Anthropic's Commercial Terms,
// and may be used to improve Anthropic's products, including training models.
// You are responsible for reviewing any code suggestions before use.

// (c) Anthropic PBC. All rights reserved. Use is subject to the Legal Agreements outlined here: https://code.claude.com/docs/en/legal-and-compliance.

// Version: 2.1.259
import"/$bunfs/root/chunk-55w4bsdv.js";import{Wet}from"/$bunfs/root/chunk-mzmfq60a.js";import"/$bunfs/root/chunk-x1rrg5j2.js";import"/$bunfs/root/chunk-jdw11prg.js";import"/$bunfs/root/chunk-56nvyfje.js";import"/$bunfs/root/chunk-1mrhsd7s.js";import{E}from"/$bunfs/root/chunk-058caznt.js";import"/$bunfs/root/chunk-97tbrkcc.js";import{t}from"/$bunfs/root/chunk-fzpv8ev5.js";import"/$bunfs/root/chunk-kn2qhfka.js";import"/$bunfs/root/chunk-xmrr4sh8.js";import"/$bunfs/root/chunk-ras23w04.js";import"/$bunfs/root/chunk-9fysw8jv.js";import{a}from"/$bunfs/root/chunk-m92n5xra.js";import"/$bunfs/root/chunk-m7w5m1w6.js";import"/$bunfs/root/chunk-6rkpsn9e.js";import{Dt}from"/$bunfs/root/chunk-enjww0fp.js";import"/$bunfs/root/chunk-nc8ww32a.js";import{GDn,P}from"/$bunfs/root/chunk-v10h0yg2.js";import{readdir as u,readFile as d,stat as p}from"fs/promises";import{homedir as m}from"os";import{join as l}from"path";async function g(){let o=P();if(!GDn.includes(o))throw Error(`Unsupported platform: ${o} - Claude Desktop integration only works on macOS and WSL.`);if(o==="macos")return l(m(),"Library","Application Support","Claude","claude_desktop_config.json");let i=a.USERPROFILE?a.USERPROFILE.replace(/\\/g,"/"):null;if(i){let e=`/mnt/c${i.replace(/^[A-Z]:/,"")}/AppData/Roaming/Claude/claude_desktop_config.json`;try{return await p(e),e}catch{}}try{try{let e=await u("/mnt/c/Users",{withFileTypes:!0});for(let r of e){if(r.name==="Public"||r.name==="Default"||r.name==="Default User"||r.name==="All Users")continue;let s=l("/mnt/c/Users",r.name,"AppData","Roaming","Claude","claude_desktop_config.json");try{return await p(s),s}catch{}}}catch{}}catch(n){t(`Failed scanning /mnt/c/Users for Claude Desktop config: ${n}`,{level:"error"})}throw Error("Could not find Claude Desktop config file in Windows. Make sure Claude Desktop is installed on Windows.")}async function O(){if(!GDn.includes(P()))throw Error("Unsupported platform - Claude Desktop integration only works on macOS and WSL.");try{let o=await g(),i;try{i=await d(o,{encoding:"utf8"})}catch(s){if(E(s)==="ENOENT")return{};throw s}let n=Dt(i);if(!n||typeof n!=="object")return{};let e=n.mcpServers;if(!e||typeof e!=="object")return{};let r={};for(let[s,c]of Object.entries(e)){if(!c||typeof c!=="object")continue;let f=Wet().safeParse(c);if(f.success)r[s]=f.data}return r}catch(o){return t(`Failed to read Claude Desktop MCP servers: ${o}`,{level:"error"}),{}}}export{O as readClaudeDesktopMcpServers};
